apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-showcase.fullname" . }}
  labels:
    {{- include "devops-showcase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-showcase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devops-showcase.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "devops-showcase.serviceAccountName" . }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
