services:
  jenkins:
    build: .
    user: root  # Required to access docker.sock
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket

volumes:
  jenkins_home:
